exports.compositoresListPage = function(clist, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Student Management</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Lista de Compositores
                    <a class="w3-btn w3-round w3-grey" href="/compositores/registo">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Nome</th><th>Período</th>
                            <th>Actions</th>
                        </tr>
                `
    for(let i=0; i < clist.length ; i++){
        pagHTML += `
                <tr>
                    <td>${clist[i].id}</td>
                    <td>
                        <a href="/compositores/${clist[i].id}">
                            ${clist[i].nome}
                        </a>
                    </td>
                    <td><a href="http://localhost:8676/periodos/${clist[i].periodo.id}">${clist[i].periodo.id}</a></td>
                    <td>
                        [<a href="/compositores/edit/${clist[i].id}">Edit</a>][<a href="/compositores/delete/${clist[i].id}">Delete</a>]
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
            <div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by EngWeb2024 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

exports.compositorFormPage = function(d,periodoList){
    page = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Student Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Student Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                        <label>Periodo</label>
                        <input class="w3-input w3-round" list="periodos" name="periodo"/>
                        <datalist id = "periodos">
                        `
    periodoList.forEach(nomePeriodo =>{
        page += `<option value="${nomePeriodo.nome}">
        `
    })
        page +=         `
                        </datalist>
                        <label>Data de Nascimento</label>
                        <input class="w3-input w3-round" type="date" name="dataNasc"/>
                        <label>Data de Óbito</label>
                        <input class="w3-input w3-round" type="date" name="dataObito"/>
                        <label>Descrição</label>
                        <input class="w3-input w3-round" type="text" name="bio"/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
    `
    return page
}

exports.compositorFormEditPage = function(c, d,periodoList){
    var page = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Student Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Student Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${c.id}"/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${c.nome}"/>
                        <label>Periodo</label>
                        <input class="w3-input w3-round" list="periodos" name="periodo" value="${c.periodo.name}"/>
                        <datalist id = "periodos">
                        `
    periodoList.forEach(nomePeriodo =>{
        page += `<option value="${nomePeriodo.nome}">
                `
    })
      
    page +=             `
                        </datalist>
                        <label>Data de Nascimento</label>
                        <input class="w3-input w3-round" type="date" name="dataNasc" value="${c.dataNasc}"/>
                        <label>Data de Óbito</label>
                        <input class="w3-input w3-round" type="date" name="dataObito" value="${c.dataObito}"/>
                        <label>Descrição</label>
                        <input class="w3-input w3-round" type="text" name="bio" value="${c.bio}"/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
    `
    return page
}

exports.compositorPage = function( comp, d ){
    return `
    <html>
    <head>
        <title>Compositor: ${comp.Id}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Aluno ${comp.id}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>Nome: </b> ${comp.nome}</li>
                    <li><b>Número: </b> ${comp.id}</li>
                    <li><b>Período: </b> <a href="http://localhost:8676/periodos/${comp.periodo.id}">${comp.periodo.name}</a></li>
                    <li><b>Descrição: </b> ${comp.bio}</li>
                    <li><b>Data de Nascimento: </b> ${comp.dataNasc}</li>
                    <li><b>Data de Óbito: </b> ${comp.dataObito}</li>
                </ul>
            </div>
        </div>
        <div>
            <footer class="w3-container w3-teal">
                <address>Gerado por LuizRodrigues::EngWeb2024 em ${d} - [<a href="/">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
}

exports.periodoListPage = function( plist,d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Student Management</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Lista de Períodos
                    <a class="w3-btn w3-round w3-grey" href="/periodos/registo">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Nome</th>
                            <th>Actions</th>
                        </tr>
                `
    for(let i=0; i < plist.length ; i++){
        pagHTML += `
                <tr>
                    <td>${plist[i].id}</td>
                    <td>
                        <a href="/periodos/${plist[i].id}">
                            ${plist[i].nome}
                        </a>
                    </td>
                    <td>
                        [<a href="/periodos/edit/${plist[i].id}">Edit</a>][<a href="/periodos/delete/${plist[i].id}">Delete</a>]
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by EngWeb2024 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

exports.periodoPage = function(p,d){
    var htmlPage = `
    <html>
    <head>
        <title>Período: ${p.id}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Aluno ${p.id}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>Nome: </b> ${p.nome}</li>
                    <li><b>Número: </b> ${p.id}</li>
                    `
    for (let i=0; i< p.compositores.length; i++){
        htmlPage += `<li><b>Compositor: </b> <a href="http://localhost:8676/compositores/${p.compositores[i].id}">${p.compositores[i].nome}</a></li>`
    }
                    `
                </ul>
            </div>
        </div>
        <div>
            <footer class="w3-container w3-teal">
                <address>Gerado por LuizRodrigues::EngWeb2024 em ${d} - [<a href="/">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
    return htmlPage
}

exports.periodoFormPage = function(d){
    page = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Student Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Student Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/periodos">Return</a>]</h5>
                </footer>
            
            </div>
    `
    return page
}

exports.periodoFormEditPage = function(p,d){
    page = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Student Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Student Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${p.id}"/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${p.nome}"/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/periodos">Return</a>]</h5>
                </footer>
            
            </div>
    `
    return page
}

// -------------- Error Treatment ------------------------------
exports.errorPage = function(errorMessage, d){
    return `
    <p>${d}: Error: ${errorMessage}</p>
    `
}
